#!/usr/bin/env bash
# Python bridge setup for OmaMovie - replaces Rust cargo/SLSA flow.
# Creates a shim at .runtime/omamovie-bridge that forwards to bridge/python.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${INSTALL_DIR:-$DIR/.runtime}"
BIN="omamovie-bridge"
VERSION="$(jq -er '.version' "$DIR/manifest.json")"
VERSION_FILE="$INSTALL_DIR/version"
REVISION_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/omamovie/plugin-revision"
PYTHON_BIN="${OMAMOVIE_PYTHON:-python3}"

say()  { printf '\033[1;36m[omamovie]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[omamovie]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[omamovie]\033[0m %s\n' "$*"; exit 1; }

command -v mpv >/dev/null 2>&1 || command -v vlc >/dev/null 2>&1 ||
  warn "no media player found - install one with: omarchy pkg add mpv"

if ! command -v "$PYTHON_BIN" >/dev/null 2>&1; then
  fail "python3 not found - install with: omarchy pkg add python (tried $PYTHON_BIN)"
fi

# Show version
PY_VER="$("$PYTHON_BIN" --version 2>&1 | head -n1 || echo "python unknown")"
say "using $PY_VER at $(command -v "$PYTHON_BIN")"

mkdir -p "$INSTALL_DIR"

record_plugin_revision() {
  local revision
  revision="$(git -C "$DIR" rev-parse HEAD 2>/dev/null || printf '%s' "$VERSION")"
  mkdir -p "$(dirname "$REVISION_FILE")"
  if [[ ! -f "$REVISION_FILE" || $(<"$REVISION_FILE") != "$revision" ]]; then
    printf '%s\n' "$revision" >"$REVISION_FILE.new"
    mv -f "$REVISION_FILE.new" "$REVISION_FILE"
  fi
}

LOCK_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/omamovie/setup.lock"
mkdir -p "$(dirname "$LOCK_FILE")"
exec 9>"$LOCK_FILE"
flock -w 180 9 || { warn "another install is already running"; exit 0; }

# If legacy Rust binary exists but version matches, we still want to replace with python shim
# Check if current BIN is already a python shim and version matches -> already installed
is_python_shim() {
  [[ -f "$INSTALL_DIR/$BIN" ]] && grep -q "bridge/python" "$INSTALL_DIR/$BIN" 2>/dev/null
}

if [[ -x "$INSTALL_DIR/$BIN" && -f "$VERSION_FILE" && $(<"$VERSION_FILE") == "$VERSION" ]] && is_python_shim; then
  say "bridge $VERSION is already installed (python)"
  # verify ping still works
  if "$INSTALL_DIR/$BIN" '{"cmd":"ping"}' 2>/dev/null | grep -q '"ok":true'; then
    record_plugin_revision
    exit 0
  else
    warn "existing shim failed ping - reinstalling"
  fi
fi

# Handle deprecated env flags gracefully
if [[ "${OMAMOVIE_BUILD_FROM_SOURCE:-0}" == "1" ]]; then
  say "OMAMOVIE_BUILD_FROM_SOURCE=1 is deprecated with python backend - ignoring (python source is directly used)"
fi
if [[ "${OMAMOVIE_ALLOW_PREBUILT:-0}" == "1" ]]; then
  warn "OMAMOVIE_ALLOW_PREBUILT is deprecated - python bridge does not use prebuilt ELFs"
fi

# Verify python bridge source exists
PY_ENTRY="$DIR/bridge/python/__main__.py"
if [[ ! -f "$PY_ENTRY" ]]; then
  fail "python bridge not found at $PY_ENTRY"
fi

# Optional: ensure python bridge is syntactically valid
if ! "$PYTHON_BIN" -m py_compile "$PY_ENTRY" 2>/dev/null; then
  warn "py_compile failed for $PY_ENTRY - continuing anyway"
fi

# Try to ensure 'requests' is available (optional, fallback to urllib)
NEEDS_REQUESTS=0
if ! "$PYTHON_BIN" -c "import requests" 2>/dev/null; then
  if [[ -s "$DIR/bridge/python/requirements.txt" ]] && grep -q "requests" "$DIR/bridge/python/requirements.txt"; then
    NEEDS_REQUESTS=1
  else
    # requests is optional; we will use urllib fallback
    say "python 'requests' not found - using stdlib urllib (no pip needed)"
  fi
fi

if [[ $NEEDS_REQUESTS -eq 1 ]]; then
  say "installing python dependencies..."
  # Prefer pip --target to avoid needing venv or --break-system-packages
  PIP_OK=0
  if "$PYTHON_BIN" -m pip --version >/dev/null 2>&1; then PIP_OK=1; fi
  if [[ $PIP_OK -eq 0 && -x "$HOME/.local/bin/pip" ]]; then PIP_OK=1; PYTHON_BIN="$PYTHON_BIN"; fi
  if [[ $PIP_OK -eq 1 ]]; then
    mkdir -p "$INSTALL_DIR/python"
    if "$PYTHON_BIN" -m pip install --target "$INSTALL_DIR/python" -r "$DIR/bridge/python/requirements.txt" --quiet 2>&1 | head -n20; then
      say "pip install completed into $INSTALL_DIR/python"
    else
      warn "pip install failed - continuing with stdlib urllib fallback"
    fi
  else
    warn "pip not available - continuing with stdlib urllib fallback (install python-pip if you want requests)"
  fi
fi

# Create shim that forwards to python bridge
# It will use PYTHONPATH to find .runtime/python if we installed there
say "installing python shim to $INSTALL_DIR/$BIN"

cat >"$INSTALL_DIR/$BIN.new" <<EOF2
#!/usr/bin/env bash
# Auto-generated by omamovie-setup.sh - do not edit
set -euo pipefail
DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
# If we installed pip deps into .runtime/python, add to PYTHONPATH
if [[ -d "\$DIR/.runtime/python" ]]; then
  export PYTHONPATH="\$DIR/.runtime/python:\${PYTHONPATH:-}"
fi
# Also ensure bridge/python is findable
export PYTHONPATH="\$DIR:\${PYTHONPATH:-}"
exec "$PYTHON_BIN" "\$DIR/bridge/python/__main__.py" "\$@"
EOF2

chmod +x "$INSTALL_DIR/$BIN.new"
mv -f "$INSTALL_DIR/$BIN.new" "$INSTALL_DIR/$BIN"

# Also ensure direct directory execution works (for Panel fallback): create wrapper that allows `python3 bridge/python` as package
# The shim already handles args; also test that `python3 bridge/python` works via __main__.py being inside folder
# No extra work needed - `python3 $DIR/bridge/python` will auto-run __main__.py

printf '%s\n' "$VERSION" >"$VERSION_FILE.new"
mv -f "$VERSION_FILE.new" "$VERSION_FILE"

say "installed $INSTALL_DIR/$BIN (python shim, $PY_VER)"

if "$INSTALL_DIR/$BIN" '{"cmd":"ping"}' 2>/dev/null | grep -q '"ok":true'; then
  say "bridge OK"
else
  warn "bridge installed but did not respond to ping - check python errors:"
  "$INSTALL_DIR/$BIN" '{"cmd":"ping"}' || true
  fail "bridge ping failed"
fi

record_plugin_revision
