#!/usr/bin/env bash
# Python bridge setup for OmaMovie - replaces Rust cargo/SLSA flow.
# Scope: creates shim at .runtime/omamovie-bridge forwarding to bridge/python
# and writes version/revision files. No system modification beyond .runtime.
# Prerequisites (python3, mpv) are manual per README - installer only warns.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${INSTALL_DIR:-$DIR/.runtime}"
BIN="omamovie-bridge"
VERSION="$(jq -er '.version' "$DIR/manifest.json")"
VERSION_FILE="$INSTALL_DIR/version"
REVISION_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/omamovie/plugin-revision"
PYTHON_BIN="${OMAMOVIE_PYTHON:-python3}"

say()  { printf '\033[1;36m[omamovie]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[omamovie]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[omamovie]\033[0m %s\n' "$*"; exit 1; }

command -v mpv >/dev/null 2>&1 || command -v vlc >/dev/null 2>&1 ||
  warn "no media player found - mpv is required for playback (see README)"

if ! command -v "$PYTHON_BIN" >/dev/null 2>&1; then
  fail "python3 not found (tried $PYTHON_BIN) - see README for prerequisites"
fi

# Show version
PY_VER="$("$PYTHON_BIN" --version 2>&1 | head -n1 || echo "python unknown")"
say "using $PY_VER at $(command -v "$PYTHON_BIN")"

mkdir -p "$INSTALL_DIR"

record_plugin_revision() {
  local revision
  revision="$(git -C "$DIR" rev-parse HEAD 2>/dev/null || printf '%s' "$VERSION")"
  mkdir -p "$(dirname "$REVISION_FILE")"
  if [[ ! -f "$REVISION_FILE" || $(<"$REVISION_FILE") != "$revision" ]]; then
    printf '%s\n' "$revision" >"$REVISION_FILE.new"
    mv -f "$REVISION_FILE.new" "$REVISION_FILE"
  fi
}

LOCK_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/omamovie/setup.lock"
mkdir -p "$(dirname "$LOCK_FILE")"
exec 9>"$LOCK_FILE"
flock -w 180 9 || { warn "another install is already running"; exit 0; }

# If legacy Rust binary exists but version matches, we still want to replace with python shim
# Check if current BIN is already a python shim and version matches -> already installed
is_python_shim() {
  [[ -f "$INSTALL_DIR/$BIN" ]] && grep -q "bridge/python" "$INSTALL_DIR/$BIN" 2>/dev/null
}

if [[ -x "$INSTALL_DIR/$BIN" && -f "$VERSION_FILE" && $(<"$VERSION_FILE") == "$VERSION" ]] && is_python_shim; then
  say "bridge $VERSION is already installed (python)"
  # verify ping still works
  if "$INSTALL_DIR/$BIN" '{"cmd":"ping"}' 2>/dev/null | grep -q '"ok":true'; then
    record_plugin_revision
    exit 0
  else
    warn "existing shim failed ping - reinstalling"
  fi
fi

# Handle deprecated env flags gracefully (prebuilt removed)
if [[ "${OMAMOVIE_BUILD_FROM_SOURCE:-0}" == "1" || "${OMAMOVIE_ALLOW_PREBUILT:-0}" == "1" ]]; then
  say "OMAMOVIE_BUILD_FROM_SOURCE/ALLOW_PREBUILT is deprecated with python backend - ignoring"
fi

# Verify python bridge source exists
PY_ENTRY="$DIR/bridge/python/__main__.py"
if [[ ! -f "$PY_ENTRY" ]]; then
  fail "python bridge not found at $PY_ENTRY"
fi

# Optional: ensure python bridge is syntactically valid
if ! "$PYTHON_BIN" -m py_compile "$PY_ENTRY" 2>/dev/null; then
  warn "py_compile failed for $PY_ENTRY - continuing anyway"
fi

# 'requests' is optional — stdlib urllib is fallback
if ! "$PYTHON_BIN" -c "import requests" 2>/dev/null; then
  say "python 'requests' not found - using stdlib urllib"
fi

# Create shim that forwards to python bridge
# It will use PYTHONPATH to find .runtime/python if we installed there
say "installing python shim to $INSTALL_DIR/$BIN"

cat >"$INSTALL_DIR/$BIN.new" <<EOF2
#!/usr/bin/env bash
# Auto-generated by omamovie-setup.sh - do not edit
set -euo pipefail
DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
export PYTHONPATH="\$DIR:\${PYTHONPATH:-}"
exec "$PYTHON_BIN" "\$DIR/bridge/python/__main__.py" "\$@"
EOF2

chmod +x "$INSTALL_DIR/$BIN.new"
mv -f "$INSTALL_DIR/$BIN.new" "$INSTALL_DIR/$BIN"

# Also ensure direct directory execution works (for Panel fallback): create wrapper that allows `python3 bridge/python` as package
# The shim already handles args; also test that `python3 bridge/python` works via __main__.py being inside folder
# No extra work needed - `python3 $DIR/bridge/python` will auto-run __main__.py

printf '%s\n' "$VERSION" >"$VERSION_FILE.new"
mv -f "$VERSION_FILE.new" "$VERSION_FILE"

say "installed $INSTALL_DIR/$BIN (python shim, $PY_VER)"

if "$INSTALL_DIR/$BIN" '{"cmd":"ping"}' 2>/dev/null | grep -q '"ok":true'; then
  say "bridge OK"
else
  warn "bridge installed but did not respond to ping - check python errors:"
  "$INSTALL_DIR/$BIN" '{"cmd":"ping"}' || true
  fail "bridge ping failed"
fi

record_plugin_revision
